### ISSUE TITLE
[ERROR] admin_request#generate_upload_url (ActiveRecord::RecordInvalid)

### ISSUE THREAD

**Issue by garethrees** [mysociety/belgium-theme#92]
```
An ActiveRecord::RecordInvalid occurred in admin_request#generate_upload_url:

translation missing: fr-BE.activerecord.errors.messages.record_invalid
app/controllers/admin_request_controller.rb:141:in `generate_upload_url'


-------------------------------
Request:
-------------------------------

* URL : https://transparencia.be/admin/requests/1/generate_upload_url
* HTTP Method: POST
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"REDACTED", "incoming_message_id"=>"465", "commit"=>"Generate and take me there", "controller"=>"admin_request", "action"=>"generate_upload_url", "id"=>"1"}
* Timestamp : 2018-09-02 12:31:23 +0200
* Rails root : /REDACTED/alaveteli-2018-08-21T14-44-20

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_request_controller.rb:141:in `generate_upload_url'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'

**Comment by garethrees** [comment]
Slightly different stack trace:

```
An ActiveRecord::RecordInvalid occurred in admin_request#generate_upload_url:

La validation a échoué : Province Veuillez sélectionner votre province
app/controllers/admin_request_controller.rb:134:in `generate_upload_url'

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_request_controller.rb:134:in `generate_upload_url'
app/controllers/application_controller.rb:118:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```
