### ISSUE TITLE
[ERROR] request#new (I18n::MissingInterpolationArgument) "missing interpolation argument

### ISSUE THREAD

**Issue by garethrees** [mysociety/belgium-theme#99]
```
An I18n::MissingInterpolationArgument occurred in request#new:

missing interpolation argument "info_request_law_u full" in {:info_request_law_used_full=>"Openbaarheid van bestuur"} ("Jammergenoeg hebben wij geen werkend adres {{info_request_law_u full}} \nvoor" given)
lib/i18n_fixes.rb:35:in `block in gettext_interpolate'

-------------------------------
Request:
-------------------------------

* URL : https://transparencia.be/nl_BE/new/cabinet_du_ministre_rene_collin_ministre_de_lagriculture_de_la_nature_de_la_foret_de_la_ruralite_du_tourisme_du_patrimoine_et_delegue_a_la_grande_region
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"new", "url_name"=>"cabinet_du_ministre_rene_collin_ministre_de_lagriculture_de_la_nature_de_la_foret_de_la_ruralite_du_tourisme_du_patrimoine_et_delegue_a_la_grande_region", "locale"=>"nl_BE"}
* Timestamp : 2018-11-04 10:10:04 +0100

-------------------------------
Backtrace:
-------------------------------

lib/i18n_fixes.rb:35:in `block in gettext_interpolate'
lib/i18n_fixes.rb:31:in `gsub'
lib/i18n_fixes.rb:31:in `gettext_interpolate'
lib/i18n_fixes.rb:11:in `_'
app/views/request/new_bad_contact.html.erb:6:in `_app_views_request_new_bad_contact_html_erb__2572500083426566883_70352806094720'
app/controllers/request_controller.rb:1086:in `render_new_compose'
app/controllers/request_controller.rb:322:in `new'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
So... I've made a quick stab at a [basic checking script](https://gist.github.com/lizconlan/2e19c77db15f116cfc775c315ee8ccd2) and it looks like there are currently 5 errors of this type to fix, some easier (for a non Dutch speaker) than others:

(Not the actual script output, that's currently much messier. Also the correct thing - note mostly to self - to do here is to fix the problems in Transifex and reimport rather than updating the `app.po` file. The output here is purely for error identification.)

```
Interpolation argument error at line 1182
msgid "From the request page, try replying to a particular message, rather than sending a general followup. If you need to make a general followup, and know an email which will go to the right place, please <a href=\"{{url}}\">send it to us</a>."
msgstr "Probeer op de aanvraagpagina te antwoorden op een bepaald bericht in plaats\\n van een algemeen follow-up bericht te versturen. Als u een algemene follow-up wil doen en u kent\\n het juiste e-mailadres, </a>stuur het dan naar ons door</a>."

Interpolation argument error at line 3064
msgid "The response to your request has been <strong>delayed</strong>. You can say that, by law, the authority should normally have responded <strong>promptly</strong> and by <strong>{{date}}</strong>"
msgstr "Het antwoord op uw vraag is <strong>vertraagd</strong>. Het is zo dat, wettelijk gezien, de overheidsinstelling\\n <strong> snel</strong> had moeten antwoorden en"

Interpolation argument error at line 3557
msgid "Unfortunately, we do not have a working {{info_request_law_used_full}} address for"
msgstr "Jammergenoeg hebben wij geen werkend adres {{info_request_law_u full}} voor"

Interpolation argument error at line 3927
msgid "You are already subscribed to any <a href=\"{{successful_requests_url}}\">successful requests</a>."
msgstr "U bent reeds ingeschreven voor alle <a href=\"{{new_requests_url}}\">succesvol afgehandelde aanvragen</a>."

Interpolation argument error at line 4510
msgid "unknown status {{state}}"
msgstr "status onbekend {{status}}"
```

**Comment by lizconlan** [comment]
Hey, while you're fixing translations - fr_BE also has:

```
Interpolation argument error at line 3078
msgid "The response to your request has been <strong>delayed</strong>. You can say that, by law, the authority should normally have responded <strong>promptly</strong> and by <strong>{{date}}</strong>"
msgstr "La réponse à votre demande a été <strong>retardée</strong>. Vous pouvez indiquer que légalement l'autorité publique aurait dû répondre <strong>rapidement</strong> et "
```

**Comment by lizconlan** [comment]
>  the correct thing - note mostly to self - to do here is to fix the problems in Transifex and reimport

Or would be if this they were on the latest version - actually need to patch the file and try to backport into Transifex where those same strings still exist

**Comment by lizconlan** [comment]
Closed by https://github.com/mysociety/alaveteli/releases/tag/0.31.0.6
